const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "emailaddress",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "first_name",
    labelFor: "first_name",
    id: "first_name",
    name: "first_name",
    type: "text",
    autoComplete: "first_name",
    isRequired: true,
    placeholder: "first_name",
  },
  {
    labelText: "last_name",
    labelFor: "last_name",
    id: "last_name",
    name: "last_name",
    type: "text",
    autoComplete: "last_name",
    isRequired: true,
    placeholder: "last_name",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "emailaddress",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirmpassword",
    name: "confirmpassword",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

export { loginFields, signupFields };
